
version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    links:
      - mongodb
    depends_on:
      - mongodb
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    links:
      - backend
    depends_on:
      - backend

